#!/usr/bin/env groovy

@Library('shared-library@main') _ 

pipeline{
    agent any
	
	stages{
	  stage('mvn Stage'){
			steps{
				
					sh '''
          cd StudentHandson
          mvn clean install 
    '''
		    }
	    }
	    stage ('Check logs') {
                    steps {
                        filterLogs ('WARNING', 10)
                    }
                }
	  stage('Compile Stage'){
			steps{
				
					sh '''
          cd StudentHandson
          mvn clean compile 
    '''
		    }
	    }
	    
	    stage('QA test Stage'){
			steps{
					sh '''
          cd StudentHandson
          mvn clean test package sonar:sonar
    '''
				}
		    }
		     stage('Junit test Stage'){
			steps{
				
				junit 'StudentHandson/target/surefire-reports/*.xml'
		    }
	    }
	    stage('upload war to nexus'){
			steps{
				
				nexusArtifactUploader artifacts: [
				[
				  artifactId: 'StudentHandson', 
				  classifier: '', 
				  file: 'StudentHandson/target/StudentHandson-0.0.1-SNAPSHOT.war', 
				  type: 'WAR']
				 ], 
				 credentialsId: 'nexus', 
				 groupId: 'h', 
				 nexusUrl: '192.168.56.108:8081', 
				 nexusVersion: 'nexus3', 
				 protocol: 'http', 
				 repository: 'Student-project', 
				 version: '0.0.1-SNAPSHOT'
		    }
	    }
	  stage('ansible-deploy'){
	      steps{
	          ansiblePlaybook credentialsId: 'ansible-privateKey', disableHostKeyChecking: true, installation: 'ansible', inventory: 'StudentHandson/dev.inv', playbook: 'StudentHandson/Test.yml'
	      }
	  }
	    
	}
}
